version: "3"
services:
  todo-list:
    build: .
    command: ./setup.sh ./todo-list
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080
  db:
    restart: always
    image: postgres:alpine
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - ./db/.env
    ports:
      - 5436:5432
