name:     try-heroku
version:  0.0.1
category: Learning
author:   Aliaksei Valatouski

executables:
  todo-list:
    source-dirs: app
    main:        Main.hs
    other-modules:
      - DB
      - Types
    dependencies:
      - base >= 4.12
      - blaze-html
      - bytestring
      - http-types
      - parsec
      - postgresql-simple
      - text
      - wai
      - wai-extra
      - wai-middleware-static
      - warp
    default-extensions:
      - BlockArguments
      - DerivingStrategies
      - FlexibleContexts
      - OverloadedStrings
      - RecordWildCards
